export const enum RouterName {
    Home = "/home",
    Info = "/info",
    Song = "/song",
    Singer = "/singer",
    SongList = "/songList",
    ListSong = "/listSong",
    Comment = "/Comment",
    Consumer = "/consumer",
    Music = "/music",
    Collect = "/collect",
    Error = "/404",
    SignIn = "/",
    SignOut = "0",
}
