spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://10.50.136.116:3306/soin-music?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: root
  banner:
    charset: UTF-8
  redis:
    host: localhost
    username: xxxx
    password: 123456
    port: 6379
    database: 0
#swagger开关
swagger:
  switch: false
#指定打印sql等级
logging:
  level:
    org:
      soin:
        biz:
          mapper: info
mybatis-plus:
  mapper-locations: classpath:/org/soin/core/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
