server:
  port: 8083
spring:
  profiles:
    active: executor-local
    group:
      dev:
        - dev
        - local
        - executor
        - executor-dev
        - executor-local
      prod:
        - prod
        - executor
        - executor-local