spring:
  profiles:
    active: local
    group:
      dev:
        - executor
        - executor-dev
        - core
        - core-dev
      local:
        - executor
        - executor-local
        - core
        - core-local

